### PR TITLE
Add TsumiLink client

### PR DESCRIPTION
**Pull request by Fyphen1223**
## Changes

Added TsumiLink client to README.md

## Why 

New client

## Checkmarks

- [x] The modified endpoints have been tested.
- [x] Used the same indentation as the rest of the project.
- [x] Still compatible with LavaLink clients.

## Additional information

If you have any additional information, write it here

### CODE REVIEW

**Comment by ThePedroo** [comment]
Oh, I'm sorry, I forgot to mention it still misses `encodeTrack` and `encodeTracks` endpoints 🤦‍♂️

**Review by ThePedroo — APPROVED** [review]

**Comment by ThePedroo** [comment]
Already going to merge to avoid posterior conflicts with my rebases

**Comment by Fyphen1223** [comment]
wait wait wait wait, It's tsumi, not tsunami lmao

**Comment by ThePedroo** [comment]
LMAO, I'll rebase later

**Pull request merged**
