### PR TITLE
Add TsumiLink client

### PR DESCRIPTION
**Pull request by Fyphen1223**
## Changes

Add TsumiLink client to README

## Why 

Add new client

## Checkmarks

- [x] The modified endpoints have been tested.
- [x] Used the same indentation as the rest of the project.
- [x] Still compatible with LavaLink clients.

### CODE REVIEW

**Comment by ThePedroo** [comment]
Heads up -- that are some points that doesn't make it fully NodeLink features compatible:

- No compression
- Leaks `loadLyrics` support

I need to take further look, but you also may be interested in:

- adding support to *fetch* the node stats

Besides that, seems fine

**Comment by Fyphen1223** [comment]
k, I'll take a time to code them

**Comment by Fyphen1223** [comment]
loadLyrics implemented, getting stats implemented

**Comment by ThePedroo** [comment]
Could you drop the commits from your repository so that they don't conflict here?

**Pull request closed without merging**
